# -*- coding: utf-8 -*-
"""Car_Sales_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DAFX64VU1QsR6_AaRa0WbzMuNuor7NDl
"""

import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score as acs

df = pd.read_csv('https://raw.githubusercontent.com/shivjain123/Car-Sales_CSV/master/Car_Sales.csv')

df.head()

df.describe()

df = df.dropna()
X = df[["EngineSize", "Cylinders", "Horsepower", "MPG_City", "MPG_Highway", "Weight", "Wheelbase", "Length"]]
y_df = df["MSRP"]

y_list = y_df.tolist()
y_int_list = list()

for r in y_list:
  replaced = r.replace('$', '')
  replaced = replaced.replace(',', '')
  y_int_list.append(int(replaced))

y_int_array = np.array(y_int_list)
X_train, X_test, y_train, y_test = tts(X, y_int_array, train_size = 0.75, random_state = 42)

reg = LinearRegression()
reg.fit(X_train, y_train)

result_prediction = reg.predict(X_test)